name = "stock-history"
main = "src/server.ts"
compatibility_date = "2024-04-03"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "stock-history-db"
database_id = "fa96a638-6d1c-46b8-a639-c9438156b3d3" # Placeholder ID for local/production setup
migrations_dir = "drizzle/migrations"

